from datasets import Split

ARTIST_NAMES_LOOKUP = {
    "a.-john-jackson": "john-jackson",
    "allan-d'arcangelo": "allan-d-arcangelo",
    "andrea-del-verocchio": "andrea-del-verrochio",
    "angelica-kauffmann": "angelica-kauffman",
    "anne-louis-girodet-trioson": "anne-louis-girodet",
    "antoine-le-nain": "le-nain-brothers",
    "antonio-allegri-da-correggio": "correggio",
    "barnadino-pinturicchio": "pinturicchio",
    "charles-lebrun": "charles-le-brun",
    "charles-marion-russell": "charles-m-russell",
    "david-cox-den-eldre": "david-cox",
    "david-cox-jr.": "david-cox",
    "david-teniers-ar-yaouankan": "david-teniers-the-younger",
    "david-teniers-gaztea": "david-teniers-the-younger",
    "david-teniers-la-pli-juna": "david-teniers-the-younger",
    "edward-henry,-i-potthast": "edward-henry-potthast",
    "edward-r.-taylor": "edward-r-taylor",
    "emilio-pettoruti": "pettoruti",
    "ferdinand-georg-waldmuller": "ferdinand-georg-waldm-ller",
    "francesc-masriera-i-manovens": "francesc-masriera",
    "francesco-de'-rossi": "francesco-de-rossi-francesco-salviati",
    "francisco-bayeu": "francisco-bayeu-y-subias",
    "francisco-de-herrera": "francisco-herrera",
    "francisco-oller-y-cestero": "francisco-oller",
    "frank-weston-benson": "frank-w-benson",
    "frans-van-mieris": "frans-van-mieris-the-elder",
    "georgia-o'keeffe": "georgia-o-keeffe",
    "giovanni-battista-cima": "cima-da-conegliano",
    "giovanni-battista-pittoni": "giambattista-pittoni",
    "giovanni-battista-salvi": "giovanni-battista-salvi-da-sassoferrato",
    "giovanni-battista-salvi-sassoferrato": "giovanni-battista-salvi-da-sassoferrato",
    "hans-holbein": "hans-holbein-the-elder",
    "hans-holbein-el-joven": "hans-holbein-the-younger",
    "henry-moore": "henry-moore-ra",
    "id.-jan-brueghel": "jan-brueghel-the-elder",
    "jacopo-palma-il-vecchio": "palma-vecchio",
    "jacopo-tintoretto": "tintoretto",
    "jacques-herold": "jacques-h-rold",
    "jacques-hérold": "jacques-h-rold",
    "jan-brueghel": "jan-brueghel-the-elder",
    "jan-brueghel-den-aeldre": "jan-brueghel-the-elder",
    "jan-brueghel-gozh": "jan-brueghel-the-elder",
    "jan-brueghel-stariji": "jan-brueghel-the-elder",
    "jan-mabuse": "mabuse",
    "jean-antoine-watteau": "antoine-watteau",
    "jean-baptiste-camille-corot": "camille-corot",
    "jean-beraud-villars": "jean-beraud",
    "joan-brull-i-vinyoles": "joan-brull",
    "john-frederick,-sr.-herring": "john-frederick-herring-sr",
    "john-frederick-herring": "john-frederick-herring-sr",
    "john-miller-nicholson": "john-miller",
    "john-o'connor": "john-o-connor",
    "joseph-mallord-william-turner": "william-turner",
    "joseph-marie,-the-younger-vien": "joseph-marie-vien",
    "joseph-wright-of-derby": "joseph-wright",
    "juan-van-der-hamen-y-leon": "juan-van-der-hamen",
    "kerry-james-marshall": "kerry-james-marshal",
    "le-nain": "le-nain-brothers",
    "li-yuanjia": "li-yuan-chia",
    "louis-le-nain": "le-nain-brothers",
    "lucas-cranach": "lucas-cranach-the-elder",
    "lucas-cranach-den-eldre": "lucas-cranach-the-elder",
    "lucas-cranach-der-altere": "lucas-cranach-the-elder",
    "lucas-cranach-der-jungere": "lucas-cranach-the-elder",
    "lucas-cranach-yr-hynaf": "lucas-cranach-the-elder",
    "marco-tintoretto": "tintoretto",
    "marie-gabrielle-capet": "marie-gabrielle-capet-0",
    "mathieu-le-nain": "le-nain-brothers",
    "matthias-stomer": "matthias-stom",
    "melchior-d'hondecoeter": "melchior-d-hondecoeter",
    "melchior-de-hondecoeter": "melchior-d-hondecoeter",
    "mestre-ataide": "mestre-ata-de",
    "michelangelo-buonarroti": "michelangelo",
    "michelangelo-merisi-da-caravaggio": "michelangelo",
    "modest-cuixart-i-tapies": "modest-cuixart",
    "morris-louis-bernstein": "morris-louis",
    "nicolas-de-stael": "nicolas-de-sta-l",
    "osman-hamdi-bey": "osman-hamdi",
    "osvaldo-louis-guglielmi": "o-louis-guglielmi",
    "palma-il-vecchio": "palma-vecchio",
    "pierre-paul-prud'hon": "pierre-paul-prud-hon",
    "pierre-paul-rubens": "peter-paul-rubens",
    "pieter-bruegel-die-jongere": "pieter-brueghel-the-younger",
    "pieter-bruegel-la-joven": "pieter-brueghel-the-younger",
    "pieter-bruegel-yr-hynaf": "pieter-bruegel-the-elder",
    "pieter-brueghel": "pieter-brueghel-the-younger",
    "pieter-brueghel-mladsi": "pieter-brueghel-the-younger",
    "pieter-brueghel-yaouank": "pieter-bruegel-the-younger",
    "pieter-claesz.": "pieter-claesz",
    "raja-ravi-verma": "raja-ravi-varma",
    "ramon-casas-i-carbo": "ramon-casas",
    "rembrandt-van-rijn": "rembrandt",
    "roger-bissiere": "roger-bissi-re",
    "stuart-davis-(piktisto)": "stuart-davis",
    "suh-se-ok": "se-ok-suh",
    "victor-meirelles-de-lima": "victor-meirelles",
    "willem-cornelisz.-duyster": "willem-cornelisz-duyster",
    "william-h.-johnson": "william-h-johnson",
    "yefim-volkov": "efim-volkov",
}

ARTWORK_ARTIST_NAMES_LOOKUP = {
    ("agonyinthegarden", "adriaen-van-der-werff"): "adriaen-van-de-velde",
    (
        "allegoryoftheimmaculateconception",
        "giovanni-battista-tiepolo",
    ): "giovanni-battista-gaulli",
    ("amerrycompany", "jan-van-wijckersloot"): "jan-van-hemessen",
    ("aprocession", "pieter-bruegel-the-younger"): "pieter-brueghel-the-younger",
    ("assunzionedellavergine", "palma-vecchio"): "palma-il-giovane",
    ("astreetinthehassonaynquartercairo", "john-varley"): "john-varley-ii",
    (
        "avillagefairvillagefestivalinhonourofsainthubertandsaintanthony",
        "pieter-bruegel-the-younger",
    ): "pieter-brueghel-the-younger",
    (
        "avillagefestivalwithatheatricalperformanceandaprocessioninhonourofsthubertandstanthony",
        "pieter-bruegel-the-younger",
    ): "pieter-brueghel-the-younger",
    ("basketoffruit", "michelangelo"): "caravaggio",
    ("beweinungchristi", "palma-vecchio"): "palma-il-giovane",
    ("christinaofdenmark", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    ("christinglory", "giovanni-battista-naldini"): "giovanni-battista-gaulli",
    ("concert", "dirck-van-delen"): "dirck-van-baburen",
    ("desideriuserasmus", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    ("details", "giovanni-battista-borra"): "giovanni-battista-piranesi",
    ("dolcefarniente", "john-william-waterhouse"): "john-william-godward",
    ("edwardprinceofwales", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    (
        "eltriunfodedavidsobregoliat",
        "pieter-bruegel-the-younger",
    ): "pieter-brueghel-the-younger",
    ("erasmusofrotterdam", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    ("filippoarchinto", "titianus-vecellii"): "titian",
    ("findingofmoses", "giovanni-battista-crosato"): "giovanni-battista-tiepolo",
    ("forestlandscape", "jacob-van-ruisdael"): "jacob-van-strij",
    ("gameelsyercairo", "john-varley"): "john-varley-ii",
    ("girlwithbirds", "jean-baptiste-huet"): "jean-baptiste-greuze",
    ("girlwithflowers", "pierre-auguste-cot"): "pierre-auguste-renoir",
    ("headofamalesaint", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    ("headofawoman", "giambattista-pittoni"): "giovanni-battista-piranesi",
    ("hooimaand", "pieter-bruegel-the-younger"): "pieter-bruegel-the-younger",
    ("janeseymour", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    (
        "jeannedeboulogneduchessofberry",
        "hans-holbein-the-elder",
    ): "hans-holbein-the-younger",
    (
        "ladywithasquirrelandastarling",
        "hans-holbein-the-elder",
    ): "hans-holbein-the-younger",
    ("laiscorinthiaca", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    ("landscapewithdeadtree", "jacob-van-ruisdael"): "jacob-van-strij",
    ("landscapewithshepherds", "adriaen-van-ostade"): "adriaen-van-de-velde",
    ("landscapewithwatermill", "jacob-van-ruisdael"): "jacob-van-strij",
    ("laresurreccion", "palma-vecchio"): "palma-il-giovane",
    ("lastsupper", "andrea-del-castagno"): "andrea-del-sarto",
    ("laubergestmichel", "pieter-bruegel-the-younger"): "pieter-brueghel-the-younger",
    ("lebaindediane", "camille-corot"): "jean-baptiste-van-loo",
    (
        "manwiththemoneybagandflatterers",
        "pieter-bruegel-the-younger",
    ): "pieter-brueghel-the-younger",
    ("mariamitkind", "palma-vecchio"): "palma-il-giovane",
    ("medicalcollegehospitalcalcutta", "john-varley"): "john-varley-ii",
    ("mosquenearthebabalnasrcairo", "john-varley"): "john-varley-ii",
    ("mosqueofmohammedbeycairo", "john-varley"): "john-varley-ii",
    ("nearthegateofthezueylahcairo", "john-varley"): "john-varley-ii",
    ("ophelia", "john-william-waterhouse"): "john-william-godward",
    (
        "peasantsbeingattackedbybandits",
        "pieter-bruegel-the-younger",
    ): "pieter-brueghel-the-younger",
    ("peasantsonthecart", "pieter-bruegel-the-younger"): "pieter-brueghel-the-younger",
    ("peasantwedding", "pieter-brueghel-the-younger"): "pieter-bruegel-the-elder",
    ("penitentmagdalene", "michelangelo"): "caravaggio",
    ("portraitofachild", "camille-corot"): "pierre-auguste-renoir",
    ("portraitofafamily", "adriaen-van-der-werff"): "adriaen-van-ostade",
    ("portraitofavenetiangentleman", "titianus-vecellii"): "titian",
    (
        "portraitofbonifaciusamerbach",
        "hans-holbein-the-elder",
    ): "hans-holbein-the-younger",
    (
        "portraitofdesideriuserasmus",
        "hans-holbein-the-elder",
    ): "hans-holbein-the-younger",
    (
        "portraitoferasmusofrotterdam",
        "hans-holbein-the-elder",
    ): "hans-holbein-the-younger",
    (
        "portraitoferasmusofrotterdamwriting",
        "hans-holbein-the-elder",
    ): "hans-holbein-the-younger",
    ("portraitofhenryviii", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    ("portraitofmaffeobarberini", "michelangelo"): "caravaggio",
    ("portraitofnicholaskratzer", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    ("portraitofrobertcheseman", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    (
        "portraitofsirrichardsouthwell",
        "hans-holbein-the-elder",
    ): "hans-holbein-the-younger",
    ("portraitofsirthomasmore", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    ("portraitofthomascromwell", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    (
        "restontheflightintoegypt",
        "giovanni-battista-crespi",
    ): "giovanni-battista-piranesi",
    ("ritrattodigentiluomo", "palma-vecchio"): "palma-il-giovane",
    ("rixedepaysans", "pieter-bruegel-the-younger"): "pieter-brueghel-the-younger",
    (
        "saintcecilia",
        "giovanni-battista-tiepolo",
    ): "giovanni-battista-salvi-da-sassoferrato",
    (
        "saintpaulconduitadamasapressaconversion",
        "pieter-bruegel-the-younger",
    ): "pieter-brueghel-the-younger",
    ("selfportrait", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    ("sirhenryguildford", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    ("sprichworte", "pieter-bruegel-the-younger"): "pieter-brueghel-the-younger",
    ("stjohnthebaptist", "giovanni-battista-ortolano"): "giovanni-battista-gaulli",
    ("susannaandtheelders", "giambattista-pittoni"): "giovanni-battista-tiepolo",
    ("theambassadors", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    (
        "thebodyofthedeadchristinthetomb",
        "hans-holbein-the-elder",
    ): "hans-holbein-the-younger",
    ("thebreadeater", "pieter-bruegel-the-younger"): "pieter-brueghel-the-younger",
    ("thedeathofstpetermartyr", "titianello"): "titian",
    ("thedescentfromthecross", "jan-van-wijckersloot"): "jan-van-hemessen",
    ("thedreamofsaintjoseph", "francisco-herrera"): "francisco-de-zurbaran",
    ("thefavourite", "john-william-waterhouse"): "john-william-godward",
    ("thegirlinwhite", "george-henry-harlow"): "george-henry",
    ("themartyrdomofsaintpeter", "titianus-vecellii"): "titian",
    ("themosqueofemirmindarcairo", "john-varley"): "john-varley-ii",
    ("thesacrificeofisaac", "giovanni-battista-piazzetta"): "giovanni-battista-tiepolo",
    (
        "thetaxcollectorsoffice",
        "pieter-bruegel-the-younger",
    ): "pieter-brueghel-the-younger",
    (
        "theweddingdanceintheopenair",
        "pieter-brueghel-the-younger",
    ): "pieter-bruegel-the-elder",
    ("thewinchman", "pieter-bruegel-the-younger"): "pieter-brueghel-the-younger",
    ("titlepage", "giovanni-battista-tiepolo"): "giovanni-battista-piranesi",
    (
        "twopeasantsbindingfaggots",
        "pieter-bruegel-the-younger",
    ): "pieter-brueghel-the-younger",
    ("venusandamor", "hans-holbein-the-elder"): "hans-holbein-the-younger",
    ("winterlandscape", "jacob-van-ruisdael"): "jacob-van-strij",
    (
        "winterlandscapewithskatersandabirdtrap",
        "pieter-brueghel-the-younger",
    ): "pieter-bruegel-the-elder",
}

BAD_WIKI_TITLES_SUBSTRS_LOOKUP = [
    "Category:",
    "Template:",
    "File:",
    "Portal:",
    "Wikipedia:",
    "Category talk:",
    "Template talk:",
    "File talk:",
    "Portal talk:",
    "Wikipedia talk:",
    "List talk:",
    "User talk:",
]

BAD_WIKI_IMGS_CLIP_PROMPTS = [
    "A low-quality icon",
    "A low-quality object",
    "A broken image",
    "A single color image",
    "A badly cut-out icon",
    "A gray image with a black square",
    "A white image with black bands",
    "An icon of a country flag",
]

TYPE_WIKI_IMGS_CLIP_PROMPTS = (
    "A photo",
    "An artistic photo",
    "A painting",
    "A sculpture",
    "A print",
    "A comic",
    "An architecture",
    "A design",
    "A handicraft",
    "A drawing",
    "An illustration",
    "A ceramic",
)

STR_TO_SPLIT = {
    "train": Split.TRAIN,
    "training": Split.TRAIN,
    "test": Split.TEST,
    "testing": Split.TEST,
    "val": Split.VALIDATION,
    "valid": Split.VALIDATION,
    "validation": Split.VALIDATION,
}
