# to launch this you should override the system prompt without the card description and comment the message editing in the input function
dataset:
  _target_: artseek.data.datasets.explain_me.ExplainMeDataset
  data_dir: data/external/explain_me
  split: test
prompt: "Explain this painting in detail with three sentences: one about its content, one about its form, and one about its context. The final answer must be in the form of a JSON object with three keys: 'content', 'form', and 'context'."
out_dir: models/checkpoints/generate/explain_me_short_no_classify_no_retrieve
classify: false
retrieve: false
